# Generated by Django 3.2.4 on 2021-11-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210629_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/PlaceHolder.png', null=True, upload_to=''),
        ),
    ]
