# Generated by Django 3.2.4 on 2021-11-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='createdAt',
        ),
    ]
